vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        sport_gym:
            uri_prefix: /images/sport_gym
            upload_destination: '%kernel.project_dir%/public/images/sport_gym'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer