vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  # regarder pourquoi les images ne sont pas uploadées sur aws

  mappings:
    sport_gym:
      uri_prefix: /images/sport_gym
      upload_destination: '%kernel.project_dir%/public/images/sport_gym'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

when@prod:
  vich_uploader:
    storage: gaufrette

    mappings:
      sport_gym:
        uri_prefix: 'https://%env(AWS_BUCKET)%.s3.%env(AWS_REGION)%.amazonaws.com/%env(AWS_DIRECTORY)%'
        upload_destination: sport_gym
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
