version: '3.8'

services:
  database:
    container_name: apidatabase
    image: mysql:5.6
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "4000:8080"